### ISSUE TITLE
KeyError: 'display_url' while scraping tweets

### ISSUE THREAD

**Issue by feusagittaire** [JustAnotherArchivist/snscrape#480]
Hi! First of all, I'd like to thank you developers in advance for this algorithm! Twitter's changes in API have really made it hard to scrape for data in the platform avoiding it's limitations.

So, with that being said, I'm facing a problem when trying to get historical data from twitter. When I'm using Google Colab, it seems to work better than in my own machine. Not sure if it's due to some proxy related thing, but I was able to get little more than 500k tweets. The only problem using Colab is that python is 3.7, and so I can't use the developer version of snscrape - tweets are scraped without much metadata -. 

In the other hand, when I'm using a jupyter notebook through vscode, i was having a problem with "ScraperException error (timeout error)" problem. I get the same error when using Colab, though. Anyways, after waiting some time between scrapings, I'm now getting KeyError: 'display_url' whenever it gets to a specific tweet. 

The code is the below:

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd
import time

query = "SUS lang:pt until:2021-04-30 since:2020-01-01"
tweets = []

limit = 1000000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():

  if len(tweets) == limit:
    break
  else: 
    tweets.append(tweet)
    print(f'tweet:{tweet} \n tweets_len: {len(tweets)}')

  

df = pd.DataFrame(tweets)
```

After the tweet, the error occurs:

https://twitter.com/GoncalvesSGS/status/1387218799330537472 
 tweets_len: 6142
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)

Is there any workaround? Thanks!!

**Comment by JustAnotherArchivist** [comment]
The problematic tweet is 1387218770079404035. It looks like I inadvertently reintroduced the bug that was fixed by 0121fa51 last night, plus there's also another crash about `expanded_url` that I hadn't seen before.

**Comment by JustAnotherArchivist** [comment]
Correction: the commit I linked was about profile description links, but this crash was caused by the profile link instead. So this bug was always present previously.

**Comment by feusagittaire** [comment]
Thanks so much for the quick response! So, in that case, what u recommend me to do? I tried using try/except to try to get rid of the problematic tweet, but the code stops nonetheless when it appears.

**Comment by krowe22** [comment]
I'm still having a problem getting this to run without getting the display_url issue. I've been working on scraping tweets for a project I'm working on. I'm using a Jupyter notebook. 

miamigpqual = []

for i, tweet in enumerate(sntwitter.TwitterSearchScraper('#miamigp').get_items()):
    if i > 20000:
        break
    miamigpqual.append([tweet.date, tweet.content, tweet.user.username])

**Comment by JustAnotherArchivist** [comment]
@krowe22 Which version of snscrape?

**Comment by krowe22** [comment]
> @krowe22 Which version of snscrape?

I'm installing this:

```python3
pip install git+https://github.com/JustAnotherArchivist/snscrape.git
```

**Comment by JustAnotherArchivist** [comment]
Unable to reproduce it with the current development version. I ran it to 26k results.

**Comment by krowe22** [comment]
> Unable to reproduce it with the current development version. I ran it to 26k results.

Got it, I'll try again
